name: Auto Reload Pages

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs the job every 5 minutes

jobs:
  reload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Reload Pages
        run: |
          curl -X GET https://yourwebsite1.com
          curl -X GET https://yourwebsite2.com
          curl -X GET https://yourwebsite3.com
