name: Auto Reload Pages

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs the job every 5 minutes

jobs:
  reload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Reload Pages
        run: |
          curl -X GET https://dapper-harsh-talos.glitch.me/
          curl -X GET https://daffodil-golden-citrine.glitch.me/
          curl -X GET https://muddy-honorable-buffer.glitch.me/
          curl -X GET https://ludicrous-jelly-chameleon.glitch.me/
          
